spring:
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: schema-all.sql
              create-source: metedata
  r2dbc:
    url: ${postgres-url}
    username: ${postgres-username}
    password: ${postgres-password}

server:
  port: 12000
